[phases.setup]
  nixPkgs = ["php82", "php82Packages.composer", "mysql80", "unzip"]

[phases.install]
  cmds = [
    "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
  ]

[phases.build]
  cmds = [
    "php artisan migrate --force",
    "php artisan storage:link"
  ]

[start]
  cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
  PHP_VERSION = "8.2"


